### PR TITLE
Background Image Change for all the pages

### PR DESCRIPTION
**Pull request by tanayag**
Regarding #20

### CODE REVIEW

**Comment by mbj36** [comment]
@tanayag what is id="index" referring to ?

**Comment by tanayag** [comment]
I have completely no Idea, it was there in the index.html, so I just copied, but now I guess it is working fine without id="index", even in index.html.
Should I change it? @mbj36

**Comment by mbj36** [comment]
If u could do it , it would be great :) @tanayag

**Comment by tanayag** [comment]
great
working on it :+1:

**Pull request merged**
